global-message: This is a global message for all services
#server:
 # port: ${PORT:8888}

#spring:
#  application:
#    name: config-service
# cloud:
#   config:
#     server:
#       git:
#         uri: https://github.com/royalejandro09/spring-cloud-server