#Puerto en el que se levantara nuestro servicio.
server:
  port: 8080

#Configuracion para registrarse en eureka. 
spring:
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
  cloud:
    gateway:
      routes:
        - id: gameRoute #Identificando la ruta del service de game-service
          uri: http://localhost:8082/ #URL donde se har치 el redirect segun el predicate definido
          predicates: #Reglas de an치lisis de una request
            - Path=/games/** #Predicate definido para este redirect
          #filters: 
           # - AddRequestHeader=game-request-header, custom-game-request-header
           # - AddResponseHeader=game-response-header, custom-game-response-header
        - id: libraryRoute #Identificando la ruta del service de library-service
          uri: http://localhost:8084/ #URL donde se har치 el redirect segun el predicate definido
          predicates: #Reglas de an치lisis de una request
            - Path=/libraries/** #Predicate definido para este redirect
