color: blue
eureka:
    client:
      service-url:
        defaultZone: http://eureka-service:8761/eureka
            
spring:
    zipkin:
        base-url: http://zipkin:9411/
        enabled: true
        
management:
    endpoints:
        web:
            exposure:
                include: info,health
    info:
        env:
            enabled: true
            
