server:
  port: 8082

info:
  app:
    name: movie-service
    description: Service for movies
    version: 1.0.0

queue:
  movie:
    name: Movie

spring:
  application:
    name: movie-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;
    username: sa
    password: sa
  sql:
    init:
      data-locations: classpath:import.sql
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop

  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
