server:
  port: 8086
  
spring:
  rabbitmq:
    username: guest
    password: guest
    host: rabbitmq
    port: 5672
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: tp_final
      port: 27017
      host: mongodb

queue:
  serie:
    name: Serie
  

info:
  app:
    name: serie-service
    version: 1.0.0
    description: Serie service
