server:
  port: 8086
  
spring:
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

queue:
  serie:
    name: Serie
#   data:
#     mongodb:
#       authentication-database: admin
#       username: rootuser
#       password: rootpass
#       database: tp_final
#       port: 27017
#       host: mongodb

info:
  app:
    name: serie-service
    version: 1.0.0
    description: Serie service
