#Server donde se levanta nuesta app.
server:
  port: 8084

#Confi para registrarse en Eureka
spring:
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka        
  datasource: #Conexion a BD H2. & Lectura de nuestro SQL en el proyecto para cargar datos iniciales.
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;
    username: sa
    password: sa
  sql:
    init:
      data-locations: classpath:library.sql
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop