info:
  app:
    name: gateway-service
    description: Service for the gateway
    version: 0.0.1

server:
  port: 8080
  
spring:
  cloud:
    gateway:
      routes:
        - id: movie-service
          uri: lb://movie-service
          predicates:
            - Path=/movies/**
        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/catalog/**